feat: Updated .github/workflows/helm-charts-test.y

diff --git a/.github/workflows/helm-charts-test.yml b/.github/workflows/helm-charts-test.yml
--- a/.github/workflows/helm-charts-test.yml
+++ b/.github/workflows/helm-charts-test.yml
@@ -13,7 +13,12 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
-    - uses: engineerd/setup-kind@v0.5.0
+    - name: Setup kind
+      uses: engineerd/setup-kind@v0.9.0
+      id: kind-setup
+    - name: Check kind setup
+      if: steps.kind-setup.outcome == 'failure'
+      run: echo "kind setup failed with ${{ steps.kind-setup.outcome }}" && exit 1
     - name: Testing
       run: |
         sudo kubectl cluster-info
